### ISSUE TITLE
Security Question

### ISSUE THREAD

**Issue by Sturgelose** [infinityworks/Guide_Rancher_Monitoring#9]
First, thanks a lot for the awesome package. It just does everything in one!

Now, question: why having so many ports open? I finally copied the docker-compose.json and I'm deleting all the exposed ports that I don't need to expose.

It really feels that otherwise is insecure and anyone would be able to push information (not to say pull). Maybe, there could be an option to run everything internally, or at least some instructions on how to run this in production :)

**Comment by Rucknar** [comment]
Hey @Sturgelose somehow missed the notification for this. Ports - This is intentional, because users might want to monitor it across multiple rancher environments.  I guess, it's written to work easily and for people to pick up, the hope is they can then take this and modify it to their own needs. Perhaps, like you say though it could have the option to expose just Prometheus's port. I'll take a look 👍

**Comment by pcornelissen** [comment]
I would propose to export no port by default and if some ports need to be exposed you could (and IMHO should) do this using the loadbalancers. The containers can talk to each other without having the exposed ports!

**Comment by Rucknar** [comment]
Appreciate the feedback. Shipping with no ports exposed though would render it un-usable.
I'll run through the ports below, how and why they are exposed...

* *node exporter* - Should be run with host networking, otherwise you don't get the hosts networking stats, you get the containers. Thus meaning, you need the port exposed on the host
* *Grafana* - User access to this port is required, needs to be exposed, could indeed be through a loadbalancer, it's a single target though so not sure what benefit the abstraction would add?
* *Prometheus* - Useful to be able to hit prometheus directly as a user, see above comment on grafana.

**Comment by Rucknar** [comment]
@Sturgelose Is right though, if you were to run this in production, additional steps would be required. I'll be re-factoring the entry to work with Rancher 2.0 in the future, i'll make sure the docs get some TLC at the same time.

**Comment by pcornelissen** [comment]
Hi!

I wasn't aware that the node_exporter uses host networking, so I have to check if I need to improve my firewall rules!

For grafana and prometheus access you could VPN into the cluster and access them there, which is pretty secure because these sensible UIs are not exposed at all (which is what I do). But you could just use the Rancher loadbalancer to expose the UIs as you see fit. This has the advantage that you can set http-auth and/or https etc. to secure access to the UIs

**Comment by pcornelissen** [comment]
It looks like the node exporter is not using host networking:

  node-exporter:
    image: prom/node-exporter:latest
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'

**Comment by Rucknar** [comment]
@pcornelissen good point, it should be. It was taken off due to tickets being raised about it being exposed.
https://github.com/infinityworks/Guide_Rancher_Monitoring/issues/20
Has the instructions needed to enable it.
